# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 979fd4a881de273427cca44ca3453170021fd4275b04a43fd19a67eff7834aa48f5b976054ce5b2123913885ff55458cd510fa92d0bd2f3b50e8a46c3e04ba07

test:
  secret_key_base: 6e42c12fe7b8e23d52b2cabd7fc08482166dbcab9df2108ccea7d98a3bb2e90a9a1d84a07d0ad0585b0084b43c362e0fa999885a78242934835c4b884e894d72

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
